/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sen_ndk_buildexternso_MathTest */

#ifndef _Included_com_sen_ndk_buildexternso_MathTest
#define _Included_com_sen_ndk_buildexternso_MathTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sen_ndk_buildexternso_MathTest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sen_ndk_buildexternso_MathTest_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
